### ISSUE TITLE
Addon not installing, screenshot included

### ISSUE THREAD

**Issue by cmohan0004** [Skilled-Coder/New-Jiosaavn-downloader-mozilla-addon#2]
![Screenshot (1)](https://user-images.githubusercontent.com/48414560/54286902-b3935b80-45ca-11e9-83b4-0c8a42c59f4f.png)

**Comment by Ank-Cha** [comment]
Will resolve it soon

**Comment by Ank-Cha** [comment]
Issue is resolved...check readme
